// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBgq4CSRIth-_A38CJc0Lh1ceJb47imcY',
    appId: '1:786475426433:web:2ba80515cb8dac3864a380',
    messagingSenderId: '786475426433',
    projectId: 'samruddhi-bfe68',
    authDomain: 'samruddhi-bfe68.firebaseapp.com',
    storageBucket: 'samruddhi-bfe68.appspot.com',
    measurementId: 'G-J6FNJHN97P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQJDnsunpLy9NKDPriIxutgBPlZGLpxkI',
    appId: '1:786475426433:android:76185e642e96f6df64a380',
    messagingSenderId: '786475426433',
    projectId: 'samruddhi-bfe68',
    storageBucket: 'samruddhi-bfe68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd5nanq3LrHSMYmHs-FQRCvG_XKGnmC4k',
    appId: '1:786475426433:ios:1bf92aae433534a564a380',
    messagingSenderId: '786475426433',
    projectId: 'samruddhi-bfe68',
    storageBucket: 'samruddhi-bfe68.appspot.com',
    androidClientId:
        '786475426433-r2vnaumtj2snhnh6r5m2kkmnpji7mjah.apps.googleusercontent.com',
    iosClientId:
        '786475426433-hjhqpd6q2r4mvniul06qpj1ugv5j10jp.apps.googleusercontent.com',
    iosBundleId: 'com.vcnr.samruddhi.samruddhi',
  );
}
